- We imported a hotel management dataset from Kaggle to perform data summarization and cleaning. Thoroughly cleaning the dataset is an essential first step. It ensures the data is accurate, properly formatted, and fully prepared for the subsequent Exploratory Data Analysis (EDA) phase.

In [112]:
import pandas as pd
import numpy as np

In [179]:
df = pd.read_csv(r'C:\Users\HP\Hotel_Cancellation_Case_Study\data\hotel_bookings.csv')

In [114]:
# Save the original dataframe to a new variable for backup
df_orignal = df.copy()

I duplicated the original dataset to preserve the raw data. This allows us to safely modify the copy without risking any permanent changes to the source.

In [115]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 32 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           119390 non-null  str
 1   is_canceled                     119390 non-null  int64
 2   lead_time                       119390 non-null  int64
 3   arrival_date_year               119390 non-null  int64
 4   arrival_date_month              119390 non-null  str
 5   arrival_date_week_number        119390 non-null  int64
 6   arrival_date_day_of_month       119390 non-null  int64
 7   stays_in_weekend_nights         119390 non-null  int64
 8   stays_in_week_nights            119390 non-null  int64
 9   adults                          119390 non-null  int64
 10  children                        119386 non-null  float64
 11  babies                          119390 non-null  int64
 12  meal                            119390 non-null  str
 13  country                         118902 non-null  str
 14  market_segment                  119390 non-null  str
 15  distribution_channel            119390 non-null  str
 16  is_repeated_guest               119390 non-null  int64
 17  previous_cancellations          119390 non-null  int64
 18  previous_bookings_not_canceled  119390 non-null  int64
 19  reserved_room_type              119390 non-null  str
 20  assigned_room_type              119390 non-null  str
 21  booking_changes                 119390 non-null  int64
 22  deposit_type                    119390 non-null  str
 23  agent                           103050 non-null  float64
 24  company                         6797 non-null    float64
 25  days_in_waiting_list            119390 non-null  int64
 26  customer_type                   119390 non-null  str
 27  adr                             119390 non-null  float64
 28  required_car_parking_spaces     119390 non-null  int64
 29  total_of_special_requests       119390 non-null  int64
 30  reservation_status              119390 non-null  str
 31  reservation_status_date         119390 non-null  str
dtypes: float64(4), int64(16), str(12)
memory usage: 37.9 MB

We have (rows,cloumns) = (119390,32)

In [116]:
pd.set_option('display.max_columns', 999)
df.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,3,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,4,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,C,0,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,0.0,0,BB,GBR,Corporate,Corporate,0,0,0,A,A,0,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03

In [117]:
pd.DataFrame({'Data type':df.dtypes})

                               Data type
hotel                                str
is_canceled                        int64
lead_time                          int64
arrival_date_year                  int64
arrival_date_month                   str
arrival_date_week_number           int64
arrival_date_day_of_month          int64
stays_in_weekend_nights            int64
stays_in_week_nights               int64
adults                             int64
children                         float64
babies                             int64
meal                                 str
country                              str
market_segment                       str
distribution_channel                 str
is_repeated_guest                  int64
previous_cancellations             int64
previous_bookings_not_canceled     int64
reserved_room_type                   str
assigned_room_type                   str
booking_changes                    int64
deposit_type                         str
agent                            float64
company                          float64
days_in_waiting_list               int64
customer_type                        str
adr                              float64
required_car_parking_spaces        int64
total_of_special_requests          int64
reservation_status                   str
reservation_status_date              str

we will check the data types of each column to ensure consistency. If any column contains incorrect or mismatched data types, we will convert them to their appropriate formats.

In [118]:
df.columns = df.columns.str.lower().str.replace(' ','_').str.strip()

**Checked all the columns and respective datatype. All were correct, had to check these:

1. reservation_status_date	str
2. agent	float64
3. company	float64
4. childern float

In [119]:
df.reservation_status_date.unique()
# reservation_status_date is in string format, we need to convert it to datetime format for better analysis. Let's convert it using pd.to_datetime() function.

<ArrowStringArray>
['2015-07-01', '2015-07-02', '2015-07-03', '2015-05-06', '2015-04-22',
 '2015-06-23', '2015-07-05', '2015-07-06', '2015-07-07', '2015-07-08',
 ...
 '2015-03-13', '2015-05-05', '2015-03-29', '2015-06-10', '2015-04-27',
 '2014-10-17', '2015-01-20', '2015-02-17', '2015-03-10', '2015-03-23']
Length: 926, dtype: str

In [120]:
df.reservation_status_date = pd.to_datetime(df.reservation_status_date,format='%Y-%m-%d')

In [121]:
df.reservation_status_date.dtype

#dtype('<M8[us]') means your date conversion was completely successful! It is NumPy’s internal technical notation for a 64-bit datetime object with microsecond precision.

dtype('<M8[us]')

In [122]:
df.agent.unique()[1:50]
# The agent is in float format as the data is in float. No need to convert it to int.

array([304., 240., 303.,  15., 241.,   8., 250., 115.,   5., 175., 134.,
       156., 243., 242.,   3., 105.,  40., 147., 306., 184.,  96.,   2.,
       127.,  95., 146.,   9., 177.,   6., 143., 244., 149., 167., 300.,
       171., 305.,  67., 196., 152., 142., 261., 104.,  36.,  26.,  29.,
       258., 110.,  71., 181.,  88.])

In [123]:
df.company.unique()[1:50]
# The company is in float format as the data is in float. No need to convert it to int as it is already in numeric format.

array([110., 113., 270., 178., 240., 154., 144., 307., 268.,  59., 204.,
       312., 318.,  94., 174., 274., 195., 223., 317., 281., 118.,  53.,
       286.,  12.,  47., 324., 342., 373., 371., 383.,  86.,  82., 218.,
        88.,  31., 397., 392., 405., 331., 367.,  20.,  83., 416.,  51.,
       395., 102.,  34.,  84., 360.])

In [124]:
null = df.isnull().sum()
null[null>0]

children         4
country        488
agent        16340
company     112593
dtype: int64

In [125]:
df[df.children.isnull()]

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
40600,City Hotel,1,2,2015,August,32,3,1,0,2,NaN,0,BB,PRT,Undefined,Undefined,0,0,0,B,B,0,No Deposit,NaN,NaN,0,Transient-Party,12.0,0,1,Canceled,2015-08-01
40667,City Hotel,1,1,2015,August,32,5,0,2,2,NaN,0,BB,PRT,Direct,Undefined,0,0,0,B,B,0,No Deposit,14.0,NaN,0,Transient-Party,12.0,0,1,Canceled,2015-08-04
40679,City Hotel,1,1,2015,August,32,5,0,2,3,NaN,0,BB,PRT,Undefined,Undefined,0,0,0,B,B,0,No Deposit,NaN,NaN,0,Transient-Party,18.0,0,2,Canceled,2015-08-04
41160,City Hotel,1,8,2015,August,33,13,2,5,2,NaN,0,BB,PRT,Online TA,Undefined,0,0,0,B,B,0,No Deposit,9.0,NaN,0,Transient-Party,76.5,0,1,Canceled,2015-08-09

In [126]:
df.fillna({'children':0},inplace=True)
df.head(1)

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,3,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01

In [127]:
df[df.country.isnull()][0:10]

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
30,Resort Hotel,0,118,2015,July,27,1,4,10,1,0.0,0,BB,NaN,Direct,Direct,0,0,0,A,A,2,No Deposit,NaN,NaN,0,Transient,62.0,0,2,Check-Out,2015-07-15
4127,Resort Hotel,1,0,2016,February,8,15,0,0,0,0.0,0,SC,NaN,Offline TA/TO,TA/TO,0,0,0,P,P,0,No Deposit,NaN,383.0,0,Transient,0.0,0,0,Canceled,2016-02-15
7092,Resort Hotel,1,8,2016,July,30,21,0,1,1,0.0,0,BB,NaN,Corporate,Corporate,0,0,0,A,A,0,No Deposit,NaN,204.0,0,Transient,73.0,0,2,Canceled,2016-07-20
7860,Resort Hotel,1,39,2016,August,36,30,0,5,2,0.0,0,HB,NaN,Direct,Direct,0,0,0,A,A,0,No Deposit,NaN,NaN,0,Transient,159.0,0,5,Canceled,2016-07-22
8779,Resort Hotel,1,0,2016,October,42,13,0,1,1,0.0,0,BB,NaN,Corporate,Corporate,0,0,0,A,A,0,No Deposit,NaN,457.0,0,Transient,50.0,0,0,Canceled,2016-10-13
9376,Resort Hotel,1,0,2016,November,48,21,0,0,0,0.0,0,SC,NaN,Offline TA/TO,TA/TO,0,0,0,P,P,0,No Deposit,NaN,386.0,0,Group,0.0,0,0,Canceled,2016-11-21
9610,Resort Hotel,1,4,2016,December,52,20,0,1,1,0.0,0,BB,NaN,Corporate,Corporate,0,0,0,A,D,0,No Deposit,NaN,204.0,0,Transient,30.0,0,2,Canceled,2016-12-19
9612,Resort Hotel,1,4,2016,December,52,20,0,1,1,0.0,0,BB,NaN,Corporate,Corporate,0,0,0,A,D,0,No Deposit,NaN,204.0,0,Transient,30.0,0,2,Canceled,2016-12-19
11262,Resort Hotel,1,87,2017,April,18,30,2,3,2,0.0,0,BB,NaN,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,NaN,0,Transient,48.0,0,0,Canceled,2017-02-02
11263,Resort Hotel,1,87,2017,April,18,30,2,3,2,0.0,0,BB,NaN,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,6.0,NaN,0,Transient,48.0,0,0,Canceled,2017-02-02

In [128]:
df.country.value_counts()

country
PRT    48590
GBR    12129
FRA    10415
ESP     8568
DEU     7287
       ...
NCL        1
KIR        1
SDN        1
ATF        1
SLE        1
Name: count, Length: 177, dtype: int64

In [129]:
len(df.country.unique())

178

In [130]:
df.country.fillna(df.country.mode()[0],inplace=True);

C:\Users\HP\AppData\Local\Temp\ipykernel_14176\3822171116.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df.country.fillna(df.country.mode()[0],inplace=True);

- Replaced the country with mode[0] because the missing number is 400 and mode[0] has count of 48.5k 
- We will not use KNN Imputer as we have large dataset, it will take time for computation.

In [ ]:
df.country = df.country.str.upper().str.strip()

In [75]:
df.agent.isnull().sum()

np.int64(16340)

In [133]:
df['has_agent'] = np.where(df['agent'].isnull(), 0, 1)

In [134]:
df['has_company'] = np.where(df['company'].isnull(), 0, 1)

We created two new columns, has_agent and has_company, to replace the original ID columns.
The specific agent and company IDs were irrelevant and increased computational costs. Converting this information into a binary format (1 or 0) clearly shows whether a booking involved an agent or company while optimizing performance.

In [135]:
df.hotel.unique()

<ArrowStringArray>
['Resort Hotel', 'City Hotel']
Length: 2, dtype: str

In [136]:
df['hotel'] = df.hotel.str.split().str[0]
df.hotel.unique()

array(['Resort', 'City'], dtype=object)

In [ ]:
df['children'] = df.children.astype('int')

We converted the children column from a float to an integer data type. Because the number of children cannot logically be a fractional value, this conversion ensures the data is accurate and realistic.

In [140]:
df.children.unique()

array([ 0,  1,  2, 10,  3])

In [141]:
# Create a list of summaries for each column
unique_summary = []

for i in df.columns:
    unique_vals = df[i].dropna().unique()
    total_unique = len(unique_vals)
    
    if total_unique > 5:
        preview = f"{list(unique_vals[:5])} ... (+{total_unique - 5} more)"
    else:
        preview = list(unique_vals)
        
    unique_summary.append({
        'Column Name': i,
        'Total Unique Count': total_unique,
        'Unique Values Preview': preview
    })

df_unique_map = pd.DataFrame(unique_summary)
df_unique_map

,Column Name,Total Unique Count,Unique Values Preview
0,hotel,2,"[Resort, City]"
1,is_canceled,2,"[0, 1]"
2,lead_time,479,"[np.int64(342), np.int64(737), np.int64(7), np..."
3,arrival_date_year,3,"[2015, 2016, 2017]"
4,arrival_date_month,12,"['July', 'August', 'September', 'October', 'No..."
5,arrival_date_week_number,53,"[np.int64(27), np.int64(28), np.int64(29), np...."
6,arrival_date_day_of_month,31,"[np.int64(1), np.int64(2), np.int64(3), np.int..."
7,stays_in_weekend_nights,17,"[np.int64(0), np.int64(1), np.int64(2), np.int..."
8,stays_in_week_nights,35,"[np.int64(0), np.int64(1), np.int64(2), np.int..."
9,adults,14,"[np.int64(2), np.int64(1), np.int64(3), np.int..."
10,children,5,"[0, 1, 2, 10, 3]"
11,babies,5,"[0, 1, 2, 10, 9]"
12,meal,5,"[BB, FB, HB, SC, Undefined]"
13,country,177,"['PRT', 'GBR', 'USA', 'ESP', 'IRL'] ... (+172 ..."
14,market_segment,8,"['Direct', 'Corporate', 'Online TA', 'Offline ..."
15,distribution_channel,5,"[Direct, Corporate, TA/TO, Undefined, GDS]"
16,is_repeated_guest,2,"[0, 1]"
17,previous_cancellations,15,"[np.int64(0), np.int64(1), np.int64(2), np.int..."
18,previous_bookings_not_canceled,73,"[np.int64(0), np.int64(1), np.int64(2), np.int..."
19,reserved_room_type,10,"['C', 'A', 'D', 'E', 'G'] ... (+5 more)"
20,assigned_room_type,12,"['C', 'A', 'D', 'E', 'G'] ... (+7 more)"
21,booking_changes,21,"[np.int64(3), np.int64(4), np.int64(0), np.int..."
22,deposit_type,3,"[No Deposit, Refundable, Non Refund]"
23,agent,333,"[np.float64(304.0), np.float64(240.0), np.floa..."
24,company,352,"[np.float64(110.0), np.float64(113.0), np.floa..."
25,days_in_waiting_list,128,"[np.int64(0), np.int64(50), np.int64(47), np.i..."
26,customer_type,4,"[Transient, Contract, Transient-Party, Group]"
27,adr,8879,"[np.float64(0.0), np.float64(75.0), np.float64..."
28,required_car_parking_spaces,5,"[0, 1, 2, 8, 3]"
29,total_of_special_requests,6,"[np.int64(0), np.int64(1), np.int64(3), np.int..."
30,reservation_status,3,"[Check-Out, Canceled, No-Show]"
31,reservation_status_date,926,"[Timestamp('2015-07-01 00:00:00'), Timestamp('..."
32,has_agent,2,"[0, 1]"
33,has_company,2,"[0, 1]"

We created a custom function to generate a summary DataFrame showing the unique counts and values for each column. This allows us to quickly audit our data for two critical checks: identifying impossible negative values in columns like children, and verifying that binary columns correctly contain only two distinct values.

In [139]:
df.is_canceled.value_counts()

is_canceled
0    75166
1    44224
Name: count, dtype: int64

In [143]:
df.arrival_date_year.value_counts()

# we have data of year 2015,2016 and 2017.

arrival_date_year
2016    56707
2017    40687
2015    21996
Name: count, dtype: int64

In [142]:
df.arrival_date_month.value_counts()

# we have data of all months from January to December.The count of booking is high in middle months and low in starting and ending months.

arrival_date_month
August       13877
July         12661
May          11791
October      11160
April        11089
June         10939
September    10508
March         9794
February      8068
November      6794
December      6780
January       5929
Name: count, dtype: int64

ADR stands for Average Daily Rate. It is one of the most critical metrics in the hotel industry. It tells you the average revenue earned per occupied room on a given day.

customer_type:

• Transient: A walk-in or standard individual booking. They are not part of any group, event, or long-term contract.

• Transient-Party: An individual booking, but it is explicitly linked to another transient booking (e.g., a family booking two separate rooms under different names).

• Contract: Bookings tied to a fixed, recurring allocation contract (e.g., airline pilots/crew who have a standing room agreement every week).

• Group: A block booking made for an explicit group, such as a wedding party or a tour group.

In [144]:
df.drop(columns=['agent', 'company'], inplace=True)

We converted required_car_parking_spaces and total_of_special_requests into binary indicators (1 and 0). This establishes a simple flag showing whether a customer requested parking or special treatment, making the data cleaner for our analysis.

In [145]:
# If parking spaces > 0, set to 1. Otherwise, keep it 0.
df['required_car_parking_spaces'] = (df['required_car_parking_spaces'] > 0).astype(int)

# If special requests > 0, set to 1. Otherwise, keep it 0.
df['total_of_special_requests'] = (df['total_of_special_requests'] > 0).astype(int)

In [150]:
df['country'] = df['country'].fillna(df['country'].mode()[0])

meal	5	[BB, FB, HB, SC, Undefined]

In [154]:
len(df[df['meal'] == 'Undefined'])

1169

In [155]:
df['meal'] = df['meal'].replace('Undefined', 'SC')

We remapped the meal column to resolve the "undefined" category. Because an undefined meal plan logically represents a guest who did not choose a meal package, we automatically converted all "undefined" values to "SC" (Self-Catering).

- We need to check these columns each unique values is valid/unique or not, the reason I have given after these few code.

1. reserved_room_type	10	['C', 'A', 'D', 'E', 'G'] ... (+5 more)
2. assigned_room_type	12	['C', 'A', 'D', 'E', 'G'] ... (+7 more)
3. market_segment	8	['Direct', 'Corporate', 'Online TA', 'Offline ...
4. distribution_channel	5	[Direct, Corporate, TA/TO, Undefined, GDS]
5. country

In [ ]:
df.reserved_room_type.value_counts()
# We have valid data in this column. We can keep it as it is.

reserved_room_type
A    85994
D    19201
E     6535
F     2897
G     2094
B     1118
C      932
H      601
P       12
L        6
Name: count, dtype: int64

In [ ]:
df.assigned_room_type.value_counts()
# We have valid data in this column. We can keep it as it is.

assigned_room_type
A    74053
D    25322
E     7806
F     3751
G     2553
C     2375
B     2163
H      712
I      363
K      279
P       12
L        1
Name: count, dtype: int64

In [159]:
df['country'] = df['country'].str.upper().str.strip()
df['distribution_channel'] = df['distribution_channel'].str.upper().str.strip()
df['market_segment'] = df['market_segment'].str.upper().str.strip()

In [169]:
print(f'We have {len(df.country.value_counts())} unique countries, {len(df.distribution_channel.value_counts())} unique distribution channels, and {len(df.market_segment.value_counts())} unique market segments.')

We have 177 unique countries, 5 unique distribution channels, and 8 unique market segments.

- We standardized our categorical text columns to address real-world data imperfections. String and object columns often contain hidden formatting errors, such as inconsistent capitalization or trailing spaces (e.g., "Class A" vs "class a "). By stripping whitespace and normalizing the text case, we ensure accurate value counts and unique value tracking across the entire dataset.

In [183]:
# 1. Select only the numeric columns
numeric_cols = df.select_dtypes(include=['int64', 'float64', 'Int64']).columns

# 2. Find which columns have values less than 0
negative_counts = (df[numeric_cols] < 0).sum()

# 3. Filter to display only columns that actually contain negatives
columns_with_negatives = negative_counts[negative_counts > 0]

if columns_with_negatives.empty:
    print("No negative values found in any numeric columns.")
else:
    print("Found negative values in the following columns:")
    print(columns_with_negatives)

Found negative values in the following columns:
adr    1
dtype: int64

In [172]:
df[df.adr<0]

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,has_agent,has_company
14969,Resort,0,195,2017,March,10,5,4,6,2,0,0,BB,GBR,GROUPS,DIRECT,1,0,2,A,H,2,No Deposit,0,Transient-Party,-6.38,0,0,Check-Out,2017-03-15,1,0

In [173]:
# Find rows where the value is negative and make them positive
df.loc[df['adr'] < 0, 'adr'] = df['adr'].abs()

- We verified that all numeric columns contain logically valid, non-negative values. For variables where negative quantities are physically impossible in real life (such as guest counts or room nights), we audited the unique value distributions to confirm that no corrupted or negative data entries exist.

-- We have successfully concluded our first notebook by cleaning and summarizing this real-world dataset without dropping any data. In professional data science, dropping rows or columns is a last resort that can bias results. Instead of deleting records, we carefully handled missing values by imputing them with neutral alternatives that preserve data integrity and will not negatively affect our model's output.